---
title: "Data Acquisition"
author: "Arash Amiririgi"
---

**A small database from E-bikes of  [Radon-bikes](https://www.radon-bikes.de):**



**Code:**

```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(tibble)
library(httr)
library(jsonlite)
library(purrr)
library(glue)
library(xopen)
library(rmarkdown)

## mountain E-bikes
url <- 'https://www.radon-bikes.de/e-bike/mountainbike/'
html <- read_html(url)
### model
mountain_ebike <- html %>% html_nodes(css = ".row > h2") %>%
  html_text() %>% as_tibble()
### price
mountain_ebike <- mountain_ebike %>% mutate(new_col=(html
  %>% html_nodes(css = ".currency_eur .m-serienpanel__price--active") %>% 
  html_text() %>% str_remove_all(' €')))
### column names
mountain_ebike <- mountain_ebike %>% set_names(c('model', 'price'))

## trekking Ebikes
url2 <- 'https://www.radon-bikes.de/e-bike/trekking/'
html2 <- read_html(url2)
### model
trekking_ebike <- html2 %>% html_nodes(css = ".row > h2") %>%
  html_text() %>% as_tibble()
### price
trekking_ebike <- trekking_ebike %>% mutate(new_col=(html2 %>% html_nodes(css =
  ".currency_eur .m-serienpanel__price--active") %>% 
  html_text() %>% str_remove_all(' €')))
### column names
trekking_ebike <- trekking_ebike %>% set_names(c('model', 'price'))

#### merging two tables
ebike_radon <- bind_rows(mountain_ebike, trekking_ebike)
```


**Results:**

```{r}
ebike_radon
```
